### ISSUE TITLE
Is not in the npm registry.

### ISSUE THREAD

**Issue by VladimirCores** [mwoodruff/webpack-universal-middleware#2]
Hi,
I tried to install you module but have an error

![screenshot from 2017-01-31 22 26 14](https://cloud.githubusercontent.com/assets/442111/22485069/7419b3e4-e804-11e6-9481-f492a19343eb.png)

**Comment by mwoodruff** [comment]
Oops! The command in the readme was wrong, sorry about that. The package name is webpack-universal-middleware. I'm working on that other one still...

I've updated the readme, but the command you need is:

`npm install --save-dev webpack-universal-middleware`

I'll publish the readme change to npm shortly.

Thanks for reporting this!
